version: "3.7"

services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER=asan
      - POSTGRES_PASSWORD=asan
      - POSTGRES_DB=final
    volumes:
      - truck_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  truck_db:
